services:
  jeikchat:
    build:
      context: .
      dockerfile: Dockerfile
    image: jeikchat:latest
    container_name: jeikcha
    ports:
      - "89:80"
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/backend
    restart: unless-stopped
    networks:
      - jeikchat-netw

networks:
  jeikchat-netw:
    driver: bridge
