services:
  jeikchat:
    build:
      context: .
      dockerfile: Dockerfile
    image: jeikchat:latest
    container_name: jeikcha
    ports:
      - "89:80"
    volumes:
      # ✅ 修改这里：去掉绝对路径，直接使用相对路径
      - ./backend/config:/backend/config
      - ./backend/agent/knowledges:/backend/agent/knowledges
      - ./backend/agent/mcp:/backend/agent/mcp
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/backend
    restart: unless-stopped
    networks:
      - jeikchat-networke

networks:
  jeikchat-network:
    driver: bridge